export const SLOT_MINUTES = 30;
export const IST_OFFSET_MINUTES = 330;
export const OPENING_HOUR = 10;
export const CLOSING_HOUR = 20;

export type AppointmentState = "pending" | "completed" | "cancelled";

export type RevenueAppointment = {
  startsAt: Date;
  status: AppointmentState;
  serviceName: string;
  servicePriceInr: number;
};

export function slotStartInIst(date: string, time: string): Date {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !/^\d{2}:\d{2}$/.test(time)) {
    throw new Error("Select a valid appointment date and time.");
  }

  const [year, month, day] = date.split("-").map(Number);
  const [hours, minutes] = time.split(":").map(Number);
  const localDate = new Date(Date.UTC(year, month - 1, day, hours, minutes));

  if (
    localDate.getUTCFullYear() !== year ||
    localDate.getUTCMonth() !== month - 1 ||
    localDate.getUTCDate() !== day ||
    minutes % SLOT_MINUTES !== 0 ||
    hours < OPENING_HOUR ||
    hours >= CLOSING_HOUR
  ) {
    throw new Error("That time is outside Scribe booking hours.");
  }

  return new Date(localDate.getTime() - IST_OFFSET_MINUTES * 60_000);
}

export function dayBoundsInIst(date: string) {
  const start = slotStartInIst(date, `${String(OPENING_HOUR).padStart(2, "0")}:00`);
  return {
    start,
    end: new Date(start.getTime() + 24 * 60 * 60_000),
  };
}

export function timeSlots() {
  const slots: string[] = [];
  for (let minutes = OPENING_HOUR * 60; minutes < CLOSING_HOUR * 60; minutes += SLOT_MINUTES) {
    slots.push(`${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`);
  }
  return slots;
}

/** Returns only day slots that may be safely bulk-updated without touching booked appointments. */
export function unbookedDaySlots(date: string, bookedStartsAt: Iterable<number>) {
  const booked = new Set(bookedStartsAt);
  return timeSlots()
    .map(time => slotStartInIst(date, time))
    .filter(startsAt => !booked.has(startsAt.getTime()));
}

export function appointmentSlotKey(barberId: number, startsAt: Date) {
  return `${barberId}:${startsAt.getTime()}`;
}

/** MySQL duplicate-key signatures generated by the active-slot unique index. */
export function isActiveSlotConflict(error: unknown) {
  const databaseError = error as { errno?: number; message?: string };
  return databaseError?.errno === 1062 || String(databaseError?.message ?? error).includes("uniq_appointments_active_slot");
}

/** Cancelling releases the slot; pending and completed appointments retain it. */
export function activeSlotKeyForStatus(activeSlotKey: string | null, status: AppointmentState) {
  return status === "cancelled" ? null : activeSlotKey;
}

export function revenueSummary(appointments: RevenueAppointment[], now = new Date()) {
  const startOfIstDay = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()) - IST_OFFSET_MINUTES * 60_000,
  );
  const startOfWeek = new Date(startOfIstDay);
  const weekday = (startOfWeek.getUTCDay() + 5) % 7;
  startOfWeek.setUTCDate(startOfWeek.getUTCDate() - weekday);
  const startOfMonth = new Date(startOfIstDay);
  startOfMonth.setUTCDate(1);

  const completed = appointments.filter(appointment => appointment.status === "completed");
  const totalFor = (start: Date) =>
    completed
      .filter(appointment => appointment.startsAt >= start && appointment.startsAt <= now)
      .reduce((total, appointment) => total + appointment.servicePriceInr, 0);

  return {
    dailyRevenueInr: totalFor(startOfIstDay),
    weeklyRevenueInr: totalFor(startOfWeek),
    monthlyRevenueInr: totalFor(startOfMonth),
    completedCount: completed.length,
    upcomingCount: appointments.filter(
      appointment => appointment.status === "pending" && appointment.startsAt >= now,
    ).length,
    completedByService: completed.reduce<Record<string, number>>((summary, appointment) => {
      summary[appointment.serviceName] = (summary[appointment.serviceName] ?? 0) + appointment.servicePriceInr;
      return summary;
    }, {}),
  };
}
